/kaggle/input/cifa-10/cifa-10/train
/kaggle/input/cifa-10/cifa-10/test
224
Found 50000 images belonging to 10 classes.
Found 10000 images belonging to 10 classes.
<KerasTensor shape=(None, 224, 224, 3), dtype=float32, sparse=None, name=input>
Conv 1:
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Conv 2:
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Conv 3:
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Conv 4:
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Using CBAM ne
Traceback (most recent call last):
  File "/kaggle/working/channel_and_spatial_attentions_with_cnn/train.py", line 187, in <module>
    main()
  File "/kaggle/working/channel_and_spatial_attentions_with_cnn/train.py", line 100, in main
    model = resnet50(input_shape=(args.image_size, args.image_size, args.image_channels), num_classes=classes,attention_type=args.attention_option)
  File "/kaggle/working/channel_and_spatial_attentions_with_cnn/model_cnn.py", line 32, in resnet50
    model = Model(input, output)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/tracking.py", line 26, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/models/functional.py", line 135, in __init__
    Function.__init__(self, inputs, outputs, name=name, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/ops/function.py", line 77, in __init__
    (nodes, nodes_by_depth, operations, operations_by_depth) = map_graph(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/ops/function.py", line 331, in map_graph
    raise ValueError(
ValueError: The name "Conv1_block1_Attention__CBAM__Channel_AveragePooling" is used 16 times in the model. All operation names should be unique.
